# Generated by Django 4.2.4 on 2023-08-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_stage_1', models.DateTimeField(default=False)),
                ('completed_stage_2', models.DateTimeField(default=False)),
                ('completed_stage_3', models.DateTimeField(default=False)),
                ('completed_stage_4', models.DateTimeField(default=False)),
                ('completed_stage_5', models.DateTimeField(default=False)),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
