# Generated by Django 4.2.4 on 2023-08-25 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_memberdata_completed_stage_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdata',
            name='completed_stage_1',
        ),
        migrations.AddField(
            model_name='memberdata',
            name='completiondate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='memberdata',
            name='memberposition',
            field=models.IntegerField(default=1),
        ),
    ]
