# Generated by Django 4.2.4 on 2023-08-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_memberdata_completed_stage_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdata',
            old_name='member',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='memberdata',
            name='completiondate',
        ),
        migrations.RemoveField(
            model_name='memberdata',
            name='memberposition',
        ),
        migrations.AddField(
            model_name='memberdata',
            name='member_routine',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='memberdata',
            name='member_routine_completiondate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
