# Generated by Django 4.2.4 on 2023-08-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_member_memberdata_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberData',
        ),
    ]
