# Generated by Django 4.2.4 on 2023-08-27 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_memberlastcompletehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_one_completed',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 14, 4, 23, 625113), null=True),
        ),
    ]
