# Generated by Django 4.2.4 on 2023-08-27 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_memberlastcompletehistory_session_one_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_three_completed',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 14, 6, 55, 528997), null=True),
        ),
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_two_completed',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 14, 6, 55, 528997), null=True),
        ),
        migrations.AlterField(
            model_name='memberlastcompletehistory',
            name='session_one_completed',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 14, 6, 55, 528997), null=True),
        ),
    ]
