# Generated by Django 4.2.4 on 2023-08-27 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_memberlastcompletehistory_session_three_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlastcompletehistory',
            name='session_one_completed',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 14, 24, 49, 178607), null=True),
        ),
        migrations.AlterField(
            model_name='memberlastcompletehistory',
            name='session_three_completed',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 14, 24, 49, 178607), null=True),
        ),
        migrations.AlterField(
            model_name='memberlastcompletehistory',
            name='session_two_completed',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 14, 24, 49, 178607), null=True),
        ),
    ]
