# Generated by Django 4.2.4 on 2023-08-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_memberlastcompletehistory_session_one_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_complete_10',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_complete_4',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_complete_5',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_complete_6',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_complete_7',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_complete_8',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_complete_9',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='memberlastcompletehistory',
            name='session_complete_1',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='memberlastcompletehistory',
            name='session_complete_2',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='memberlastcompletehistory',
            name='session_complete_3',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
