# Generated by Django 4.2.4 on 2023-09-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_memberlastcompletehistory_session_complete_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_complete_11',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='memberlastcompletehistory',
            name='session_complete_12',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
