# Generated by Django 4.2.4 on 2023-08-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutsessions', '0002_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='library',
        ),
    ]
